spring.application.name=altf4

# H2 Database
spring.datasource.url=jdbc:h2:mem:altf4db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite ejecutar data.sql después de crear las tablas
spring.jpa.defer-datasource-initialization=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console